---
version: '3.8'

services:
  app:
    build:
      target: app
      context: .
    depends_on:
    - db
    environment:
    - DATASOURCE_DOMAIN=db
    - DATASOURCE_PORT=5432
    - DATASOURCE_DB_NAME=aes_db
    - DATASOURCE_USERNAME=postgres
    - DATASOURCE_PASSWORD=postgres
    - FILE_UPLOAD_DIRECTORY=/app/images
    ports:
    - 8080:8080
    volumes:
    - image-volume:/app/images
  db:
    image: postgres:latest
    restart: always
    environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres
    - POSTGRES_DB=aes_db
    ports:
    - 5432:5432
    volumes:
    - db-volume:/var/lib/postgresql/data

  test:
    build:
      target: test
      context: .
    depends_on:
    - test-db
    environment:
    - DATASOURCE_DOMAIN=test-db
    - DATASOURCE_PORT=5432
    - DATASOURCE_DB_NAME=test_aes_db
    - DATASOURCE_USERNAME=postgres
    - DATASOURCE_PASSWORD=postgres
    - FILE_UPLOAD_DIRECTORY=/app/images
    volumes:
    - ./docker-test-reports:/app/build/reports
  test-db:
    image: postgres:latest
    restart: always
    environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres
    - POSTGRES_DB=test_aes_db
    ports:
    - 5433:5432

volumes:
  db-volume:
    driver: local
  image-volume:
    driver: local
