---
name: Test Project

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - uses: isbang/compose-action@v1.5.1
      with:
        compose-file: ./docker-compose.yaml
        down-flags: --volumes
        services: test
