---
name: Test Formatting

on:
  push:

jobs:
  formatting:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Run pre-commit
      uses: pre-commit/action@v3.0.0
      with:
        extra_args: --all-files
